version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=laravel"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=your_mysql_root_password"

  webserver:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      # you must create the folder nginx and inside it create a file nginx.conf. Now defualt.conf of container machine will have symbolic link with your local nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: laravel
    ports:
      - 9008:3306
    volumes:
    #You must have this folder in your project
      - ./mysql:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql


